# Generated by Django 4.2.1 on 2023-05-21 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='state',
        ),
    ]
