# Generated by Django 4.2.1 on 2023-05-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0003_user_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='idUser',
        ),
        migrations.AddField(
            model_name='ticket',
            name='nameUser',
            field=models.CharField(default='Kevin Perez', max_length=200),
        ),
    ]
