# Generated by Django 4.2.1 on 2023-05-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0004_remove_ticket_iduser_ticket_nameuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='email',
            field=models.CharField(default='kevinsteven797@gmail.com', max_length=200),
        ),
    ]
