# Generated by Django 4.2.1 on 2023-05-21 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0005_ticket_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='numTicket',
            new_name='numTickets',
        ),
    ]
